# Generated by Django 3.0.1 on 2020-04-08 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kc_app', '0003_auto_20200408_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 12, 37, 18, 495957, tzinfo=utc)),
        ),
    ]
